### ISSUE TITLE
Mimikatz integration

### ISSUE THREAD

**Issue by n8zwn** [m8r0wn/ActiveReign#2]
Have you thought about integrating mimikatz into this tool? I am sure it is not an easy feat, but I would be willing to help test. I would imagine it would need to be executed via a .net payload, but I think you know better than I. Thanks for a great tool!

**Comment by m8r0wn** [comment]
Hi @n8zwn,

Glad your liking the tools so far! I should have a push coming up soon that does a better implementation of PowerShell, including a proper invoke mimikatz module with the ability to change the default command. In addition to lots of other fun stuff :)

Would love help testing once its pushed, ill keep the issue open until then.
Thanks for your help,
m8r0wn

**Comment by m8r0wn** [comment]
Just pushed v0.1.0 with the renewed PowerShell implementation and updated modules as well. Hoping to find a better way to make this more consistent across OS versions in the future, as well as implement more ways of gaining creds! 

For now I am going to close the issue. Thanks again for your help,
m8r0wn
